src/myapp/urls.py
from django.urls import path, re_path

from myapp import views

app_name = 'crud'

urlpatterns = [
    path('', views.GreetingList.as_view(), name='greeting-list', ),
    path('new/', views.GreetingCreate.as_view(), name='greeting-create'),
    re_path('(?P<pk>\d+)/', views.GreetingDetail.as_view(), name='greeting-detail'),
    re_path('(?P<pk>\d+)/update/', views.GreetingUpdate.as_view(), name='greeting-update'),
    re_path('(?P<pk>\d+)/delete/', views.GreetingDelete.as_view(), name='greeting-delete'),

    path('version/', views.version),
    path('version/<label>/', views.version, name='myapp-version'),
]

src/urls.py
from rest_framework.routers import DefaultRouter
from django.contrib import admin

from django.conf import settings
from django.urls import path, re_path, include

from django.conf.urls.static import static

router = DefaultRouter()

app_patterns = [
    path('greetings/', include('myapp.urls')),

    path('api/v1/', include('myapp.api')),
    path('mock/v1/', include('myapp.mock')),

    path('admin/', admin.site.urls),
]

app_patterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.SITE_PATH:
    urlpatterns = [
        path(
            '%s/' % settings.SITE_PATH.strip('/'),
            include(app_patterns)
        ),
    ]
else:
    urlpatterns = app_patterns

if settings.DEBUG:
    import debug_toolbar

    if settings.SITE_PATH and settings.SITE_PATH.strip('/'):
        urlpatterns = [
            re_path(r'^%s/__debug__/' % settings.SITE_PATH.strip('/'), include(debug_toolbar.urls)),
        ] + urlpatterns
    else:
        urlpatterns = [
            re_path(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/myapp/models.py
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import AbstractUser

from dirtyfields import DirtyFieldsMixin


class User(AbstractUser):

    def __str__(self):
        return self.email


class Greeting(DirtyFieldsMixin, models.Model):
    name = models.CharField(max_length=50, blank=False, null=False)

    def __unicode__(self):
        return "%s" % (self.name)

    def get_absolute_url(self):
        return reverse('crud:greeting-detail', args=[str(self.id)])

    class Meta:
        ordering = ['-id']


Greeting.mock_objects = Greeting.objects.db_manager('mock')

src/myapp/forms.py
from django import forms

from log_utils import FormLoggingMixin
from .models import Greeting


class GreetingForm(FormLoggingMixin, forms.ModelForm):
    class Meta:
        model = Greeting
        fields = ['name']

src/myapp/views.py
from django.urls import reverse_lazy as django_reverse_lazy
from django.db import transaction
from django.http import HttpResponse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from rest_framework import viewsets, permissions, mixins
from rest_framework.request import Request

from log_utils import LogMixin
from myapp import format_version
from .models import Greeting
from .serializers import GreetingSerializer
from .forms import GreetingForm


class GreetingViewSet(
        mixins.ListModelMixin,
        mixins.RetrieveModelMixin,
        mixins.CreateModelMixin,
        mixins.UpdateModelMixin,
        mixins.DestroyModelMixin,
        viewsets.GenericViewSet):

    queryset = Greeting.objects.all()
    serializer_class = GreetingSerializer
    permission_classes = (permissions.IsAuthenticated,)


class LoggedGreetingViewSet(LogMixin, GreetingViewSet):
    # log any creation
    def perform_create(self, serializer):
        super(LoggedGreetingViewSet, self).perform_create(serializer)
        self.logger.info("A new greeting as been created")


class MockGreetingViewSet(GreetingViewSet):
    queryset = Greeting.mock_objects.all()

    def dispatch(self, request, *args, **kwargs):
        """
        Don't dispatch the call if the url has the "fake" arg
        """
        query_string = Request(request).query_params
        fake_code = query_string.get('fake')

        if fake_code:
            fake_code = int(fake_code)
            return HttpResponse(status=fake_code)
        else:
            # NB: the 'mock' db is configured with ATOMIC_REQUESTS = True
            sid = transaction.savepoint(using='mock')
            response = super(MockGreetingViewSet, self).dispatch(request, *args, **kwargs)
            transaction.savepoint_rollback(sid, using='mock')
            return response


class GreetingList(LogMixin, ListView):
    model = Greeting
    paginate_by = 20

    def get(self, *args, **kwargs):
        to_return = super(GreetingList, self).get(*args, **kwargs)
        self.logger.info("Get a list of greetings")
        return to_return


class GreetingCreate(CreateView):
    model = Greeting
    form_class = GreetingForm
    success_url = django_reverse_lazy('crud:greeting-list')


class GreetingDetail(DetailView):
    model = Greeting


class GreetingUpdate(UpdateView):
    model = Greeting
    form_class = GreetingForm
    success_url = django_reverse_lazy('crud:greeting-list')


class GreetingDelete(DeleteView):
    model = Greeting
    success_url = django_reverse_lazy('crud:greeting-list')


def version(request, label='version'):
    return HttpResponse(format_version(label))

src/myapp/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    </head>
    <body>
        <div class="container">
            <div class="page-header">
            <h1>Django CRUD Scaffold</h1>
            <p>Default template for generated CRUD scaffold.  You should create your own base.html in your template root, with a block named "content".</p>
            </div>
            <div class="content">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </body>
</html>  

src/myapp/templates/myapp/greeting_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h1>Delete</h1>
    <p>Are you sure you want to delete?</p>

    <form id="{{cookiecutter.nocase_model_name}}_form" method="post" action=".">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-primary" /> <a href="{% url 'crud:greeting-list' %}" class="btn btn-danger">No</a>
    </form>
{% endblock %}

src/myapp/templates/myapp/greeting_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>Detail</h1>
    <p>{{ object.name }}</p>
    <a href="{% url 'crud:greeting-list' %}">List</a>
{% endblock %}

src/myapp/templates/myapp/greeting_form.html
{% extends "base.html" %}

{% load bootstrap4 %}

{% block content %}
    <h1>Create/Update</h1>
    <form id="greeting_form" method="post" action="." class="form">
      {% csrf_token %}
      {% bootstrap_form form layout='horizontal' %}
      {% buttons %}
        <button type="submit" class="btn btn-primary">Submit</button>
      {% endbuttons %}
    </form>
{% endblock %}

src/myapp/templates/myapp/greeting_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Greetings Listing</h1>
    <a href="{% url 'crud:greeting-create' %}">Create</a>
    <ul>
        {% for object in object_list %}
            <li>
                {{ object }}
                <a href="{{ object.get_absolute_url }}">Details</a>
                <a href="{% url 'crud:greeting-update' object.pk %}">Update</a>
                <a href="{% url 'crud:greeting-delete' object.pk %}">Delete</a>
            </li>
        {% empty %}
                <p>No items.</p>
        {% endfor %}
    </ul>

    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{% url 'crud:greeting-list' %}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{% url 'crud:greeting-list' %}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}


{% endblock %}